Repository wecode-bootcamp-korea/26-2nd-StayWithMe-frontend, pull requests merged in 2021-11, with the labels that each got.

#3 [26기 신유진]Add:Nav 레이아웃
  package.json
  public/images/logo.jpg
  src/components/Nav/Nav.js
  src/pages/DetailPage/DetailPage.js
  src/styles/theme.js
  yarn.lock
Labels: Status: Accepted

#1 [26기 최병현]Add & Modify & Refactor: Conflict 요청 문제 반영 / 달력 기능 추가 및 queryPath 기능 추가
  package-lock.json
  package.json
  public/data/InfoListData.json
  public/data/infoListAddData.json
  public/images/arw-search2.png
  public/images/btn_layer_close.png
  public/images/dropdownImg.png
  src/ config.js
  src/Router.js
  src/config.js
  src/pages/InfoList/InfoFeed.js
  src/pages/InfoList/InfoList.js
  src/pages/InfoList/InfoListForm.js
  src/pages/InfoList/InfoListPage.js
  src/pages/InfoList/InfoListTemplate.js
  src/pages/InfoList/ModalSort/DateModal.js
  src/pages/InfoList/ModalSort/SlideBar.js
  src/pages/InfoList/OrderCategory.js
  src/pages/InfoList/PagingContainer.js
  src/pages/InfoList/SortBox/ModalForm.js
  src/pages/InfoList/SortBox/ModalTemplate.js
  src/pages/InfoList/SortBox/SortBoxButton.js
  src/pages/InfoList/SortBox/SortBoxFilterForm.js
  src/pages/InfoList/SortBox/SortBoxTemplate.js
  src/pages/InfoList/SubtitleTemplate.js
  src/pages/InfoList/queryModule.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
  yarn.lock
Labels: Status: Accepted

#5 Add: 카카오 소셜 로그인 완료
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/components/Auth/KakaoButton.js
  src/components/Auth/Login.js
  src/components/Auth/Oauth.js
  src/components/Auth/RedirectHandler.js
  src/pages/InfoList/InfoList.js
  yarn.lock
Labels: Status: 리뷰 요청

#7 [26기 신유진]Add : Nav 수정완료
  src/components/Nav/Nav.js
  src/pages/DetailPage/DetailPage.js
  src/styles/theme.js
Labels: Status: 수정 요청

#8 [26기 최병현]Modify: git conflict 문제 해결 / SortBox Component 및 quertModule 기능 수정
  public/images/btn_count.png
  public/images/slider_thumb.png
  src/ config.js
  src/pages/DetailPage/DetailPage.js
  src/pages/InfoList/InfoFeed.js
  src/pages/InfoList/InfoListForm.js
  src/pages/InfoList/InfoListPage.js
  src/pages/InfoList/InfoListTemplate.js
  src/pages/InfoList/ModalSort/CountPeople.js
  src/pages/InfoList/ModalSort/DateModal.js
  src/pages/InfoList/ModalSort/SlideBar.js
  src/pages/InfoList/ModalSort/StayCheckBox.js
  src/pages/InfoList/PagingContainer.js
  src/pages/InfoList/SortBox/ModalForm.js
  src/pages/InfoList/SortBox/SortBoxButton.js
  src/pages/InfoList/queryModule.js
  src/styles/theme.js
  yarn.lock
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#4 [26기 신유진] merge 요청
  package.json
  public/SliderImg/left.png
  public/SliderImg/right.png
  public/data/data.json
  public/images/nextbutton.png
  public/images/prevbutton.png
  public/index.html
  src/Router.js
  src/pages/DetailPage/BottomSlider.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/RoomInfo.js
  src/pages/DetailPage/ShowDateBox.js
  src/pages/DetailPage/Slide.js
  yarn.lock
Labels: Status: Rebase 요청
